#!/bin/sh

#---------------------------
# HYSPLIT Trajectory simulation for fire location in Southeast Atlantic
echo " " >>hysplit_dump

##define global directories
export PROGM=$HOME/hysplit/trunk/exec/
export DATDIR=$HOME/data/HYSPLIT/$confTA/smoke_era_SEA/
export PLTDIR=$HOME/plot/HYSPLIT/$confTA/smoke_era_SEA/
export ERADIR=$HOME/data/ERA/METDATA_HYSPLIT/ARLdata/

##Ensure that directories are created
mkdir -p $DATDIR
mkdir -p $PLTDIR

##Clean
rm -f arlmap
rm -f ASCDATA.CFG
rm -f CONTROL
rm -f tdump*
rm -f MESSAGE
rm -f TRAJ*
rm -f WARNING


##define output file
OUTdump=tdump_${yyyymm}${dd}_${hh}${mn}_${lat}_${lon}
OUTplot=plot_${yyyymm}${dd}_${hh}${mn}_${lat}_${lon}.ps
echo ${DATDIR}$OUTdump >>hysplit_dump
echo ${PLTDIR}$OUTplot >>hysplit_dump


#---------------------------
##Check if the data has already been calculated
if [ -f ${DATDIR}$OUTdump ]
then
  echo "$OUTdump exist"
else
#  echo "$OUTdump DO NOT exist"

#---------------------------
##Link useful data for hysplit
ln -sf $HOME/hysplit/trunk/bdyfiles/ASCDATA.CFG ./
ln -sf $HOME/hysplit/trunk/graphics/arlmap ./
#---------------------------
##Create the control file here
##cat <<'EOF' > CONTROL
##The quotes around the initial 'EOF' mean "do not expand any shell variables (etc) in the here document".
cat <<EOF > CONTROL
${yy} ${mm} ${dd} ${hh} ${mn}
1
${lat} ${lon} 250.0
240
0
10000.0
2
${ERADIR}
ERA40_${yyyymm}
${ERADIR}
ERA40_${yyyymm1}
./
tdump_001
EOF

##Run the hysplit model
echo "HYSPLIT: Computing trajectory: ${OUTdump}..."
${PROGM}hyts_std >>hysplit_dump
##Plot the data here
echo "HYSPLIT: Plotting trajectory: ${OUTplot}..."
echo "'TITLE&','Smoke Trajectory: Southern Africa&'" >LABELS.CFG
${PROGM}trajplot -v1 -l12 -itdump_001 -oplot_001.ps >>hysplit_dump

##move files
mv tdump_001 ${DATDIR}${OUTdump}
#ps2pdf plot_001.ps plot_001.pdf
mv plot_001.ps ${PLTDIR}${OUTplot}

#remove files
rm -f plot_001.ps
rm -f LABELS.CFG TRAJ.CFG MESSAGE CONTROL

if [ -f "WARNING" ]
then
  cat WARNING >> hysplit_dump
  rm WARNING
fi

fi
exit
